#! /bin/bash

# this will be the download script to fetch the various normalised pancreas datasets from a Dropbox as a zipped directory
# it contains the following files
# raw counts (generated by featureCounts) - alpha-feature_counts.tsv.gz, beta-feature_counts.tsv.gz, delta-feature_counts.tsv.gz, 
# PP-feature_counts.tsv.gz

curl -L -o RawData.zip https://www.dropbox.com/sh/kb4bvve0f4ew9l9/AABVUeItR6ZRtdPFCjx1fHeOa?dl=1
