#! /bin/bash

mkdir -p raw_data

# Fetch GSE81076 files from NCBI GEO's FTP site.

curl -L -o raw_data/GSE81076_D2_3_7_10_17.txt.gz ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE81nnn/GSE81076/suppl/GSE81076%5FD2%5F3%5F7%5F10%5F17%2Etxt%2Egz

# Fetch GSE85241 files from NCBI GEO's FTP site.

curl -L -o raw_data/GSE85241_cellsystems_dataset_4donors_updated.csv.gz ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE85nnn/GSE85241/suppl/GSE85241%5Fcellsystems%5Fdataset%5F4donors%5Fupdated%2Ecsv%2Egz

# Fetch processed GSE86473 files from a Dropbox folder, as a zipped directory
# It contains the following files with raw counts generated by featureCounts:
# - alpha-feature_counts.tsv.gz
# - beta-feature_counts.tsv.gz
# - delta-feature_counts.tsv.gz
# - PP-feature_counts.tsv.gz

mkdir -p raw_data/GSE86473
cd raw_data/GSE86473
curl -L -o raw.zip https://www.dropbox.com/sh/kb4bvve0f4ew9l9/AABVUeItR6ZRtdPFCjx1fHeOa?dl=1
unzip raw.zip
rm -f raw.zip E-MTAB-5061.sdrf.txt pancreas_refseq_rpkms_counts_3514sc.txt EMTAB5061_rpkm_counts.txt.zip pancreas-smarseq2-qcout.tsv
cd -
 
# Fetch E-MTAB-5061 data from ArrayExpress.

curl -L -o raw_data/EMTAB5061_rpkm_counts.txt.zip https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-5061/files/E-MTAB-5061.processed.1.zip
curl -L -o raw_data/E-MTAB-5061.sdrf.txt https://www.ebi.ac.uk/arrayexpress/files/E-MTAB-5061/E-MTAB-5061.sdrf.txt

cd raw_data
unzip EMTAB5061_rpkm_counts.txt.zip
rm EMTAB5061_rpkm_counts.txt.zip

cd -
