#! /bin/bash

# Fetch GSE81076 files from NCBI GEO's FTP site.

curl -L -o raw_data/GSE81076_D2_3_7_10_17.txt.gz ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE81nnn/GSE81076/suppl/GSE81076%5FD2%5F3%5F7%5F10%5F17%2Etxt%2Egz

# Fetch GSE85241 files from NCBI GEO's FTP site.

curl -L -o raw_data/GSE85241_cellsystems_dataset_4donors_updated.csv.gz ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE85nnn/GSE85241/suppl/GSE85241%5Fcellsystems%5Fdataset%5F4donors%5Fupdated%2Ecsv%2Egz

# Fetch processed GSE86473 files from a Dropbox folder, as a zipped directory
# It contains the following files with raw counts generated by featureCounts:
# - alpha-feature_counts.tsv.gz
# - beta-feature_counts.tsv.gz
# - delta-feature_counts.tsv.gz
# - PP-feature_counts.tsv.gz

curl -L -o raw_data/GSE86473.zip https://www.dropbox.com/sh/kb4bvve0f4ew9l9/AABVUeItR6ZRtdPFCjx1fHeOa?dl=1

 
